spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  datasource:
    driver-class-name: ${spring.datasource.driver-class-name}
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}

  data:
    redis:
      host: ${spring.redis.host}
      port: ${spring.redis.port}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace

jwt:
  secret: ${jwt.secret}
  expire-time:
    access-token: ${jwt.expire-time.access-token}

oauth:
  google:
    client-id: ${oauth.google.client-id}
    client-secret: ${oauth.google.client-secret}
    redirect-uri: ${oauth.google.redirect-uri}

  kakao:
    client-id: ${oauth.kakao.client-id}
    redirect-uri: ${oauth.kakao.redirect-uri}
